// The list of "things" people will compare.
// Rules: no groups of people; only things anyone can have an opinion about.
// Seeded from Wikipedia's "Vital Articles" Level 3 (the concrete, opinion-able
// sections). Grouped by theme only for readability — it's one flat list.
// Prune anything you dislike, or add your own at the end.
const THINGS = [
  // --- Food & drink ---
  "Bread",
  "Rice",
  "Corn",
  "Cheese",
  "Chocolate",
  "Meat",
  "Fruit",
  "Vegetables",
  "Sugar",
  "Salt",
  "Potatoes",
  "Beans",
  "Eggs",
  "Coffee",
  "Tea",
  "Milk",

  // --- Animals ---
  "Cats",
  "Dogs",
  "Horses",
  "Pigs",
  "Cows",
  "Sheep",
  "Chickens",
  "Fish",
  "Birds",
  "Insects",
  "Reptiles",
  "Dinosaurs",

  // --- Plants ---
  "Trees",
  "Flowers",
  "Mushrooms",

  // --- Nature & weather ---
  "Rain",
  "Snow",
  "Clouds",
  "Lightning",
  "Wind",
  "Storms",
  "Volcanoes",
  "Earthquakes",
  "Mountains",
  "Forests",
  "Deserts",
  "Islands",
  "The ocean",
  "Lakes",
  "Rivers",
  "Beaches",
  "Fire",
  "Water",

  // --- Space ---
  "The Sun",
  "The Moon",
  "Mercury",
  "Venus",
  "Earth",
  "Mars",
  "Jupiter",
  "Saturn",
  "Uranus",
  "Neptune",
  "Stars",
  "Comets",
  "Galaxies",
  "Black holes",

  // --- Materials ---
  "Gold",
  "Silver",
  "Copper",
  "Iron",
  "Steel",
  "Glass",
  "Wood",
  "Paper",
  "Plastic",
  "Rubber",
  "Cotton",

  // --- Objects & technology ---
  "Books",
  "Computers",
  "The internet",
  "Smartphones",
  "Television",
  "Radio",
  "Cameras",
  "Clocks",
  "Maps",
  "Bicycles",
  "Cars",
  "Trains",
  "Ships",
  "Airplanes",
  "Rockets",
  "Robots",
  "Knives",
  "Light bulbs",
  "Telescopes",
  "Microscopes",
  "Bridges",

  // --- Arts ---
  "Music",
  "Jazz",
  "Classical music",
  "Folk music",
  "Pop music",
  "Rock music",
  "Opera",
  "Dance",
  "Theater",
  "Film",
  "Painting",
  "Photography",
  "Sculpture",
  "Comics",
  "Animation",
  "Poetry",
  "Singing",
  "Pottery",

  // --- Games & recreation ---
  "Board games",
  "Card games",
  "Video games",
  "Toys",
  "Sports",
  "Soccer",
  "Swimming",
  "Martial arts",

  // --- Everyday things ---
  "Shoes",
  "Furniture",
  "Jewelry",
  "Sleep",
  "Color",
  "Sound",
  "Light",

  // --- Abstract & science concepts ---
  "Time",
  "Space",
  "Energy",
  "Gravity",
  "Force",
  "Motion",
  "Electricity",
  "Magnetism",
  "Matter",
  "Atoms",
  "Heat",
  "Quantum physics",
  "Evolution",
  "Love",
  "Happiness",
  "Luck",
  "Fear",
  "Beauty",
  "Freedom",
  "Peace",
  "Truth",

  // --- Sex (the act, not identity — gender/orientation stay out by choice) ---
  "Sex",
  "Orgasm",
  "Kissing",
];
